name: PR merged build and push

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths-ignore:
      - .github/**

env:
  IMAGE_NAME: spring-petclinic

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    if: github.event.pull_request.merged == true

    permissions:
      contents: write
      id-token: write
    
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4  
        with:
          fetch-depth: 0  
          fetch-tags: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
 
      - name: Configure git
        run: |
          git config user.name "github-actions-bot"
          git config user.email ""

      - name: Update tag
        id: gettag
        run: |
          TAG="$(git tag --list --sort=-v:refname | head -n 1)"
          if [ -z "$TAG" ]; then
            TAG=v0.0.0
          fi

          cat <<EOF > tagbump.py
          import semver
          import sys

          tag = sys.argv[1][1:]
          ver = semver.Version.parse(tag).bump_minor()
          print("v" + str(ver))
          EOF

          pip install semver
          NEWTAG="$(python tagbump.py $TAG)"

          git tag "$NEWTAG"
          git push origin "$NEWTAG"

          echo "NEWTAG=$NEWTAG" >> $GITHUB_ENV

      - name: Auth to GCP
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          workload_identity_provider: ${{ secrets.WIF_URL }}
          service_account: ${{ secrets.TF_SA }}
          create_credentials_file: true
          token_format: access_token
          access_token_lifetime: "360s"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.GAR_URL }}
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and push
        uses: docker/build-push-action@v6  
        with:
          push: true
          tags: ${{ secrets.GAR_URL }}/${{ env.IMAGE_NAME }}:${{ env.NEWTAG }},${{ secrets.GAR_URL }}/${{ env.IMAGE_NAME }}:latest

